# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(683, 464)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.table_second = QtWidgets.QTableWidget(Form)
        self.table_second.setObjectName("table_second")
        self.table_second.setColumnCount(0)
        self.table_second.setRowCount(0)
        self.gridLayout.addWidget(self.table_second, 0, 0, 2, 2)
        self.btn = QtWidgets.QPushButton(Form)
        self.btn.setObjectName("btn")
        self.gridLayout.addWidget(self.btn, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn.setText(_translate("Form", "Создать"))
